#!/bin/bash

#############################################################################
#
# Startscript for AnmanieSMP
# 
# Created  for Pardus
#
#############################################################################


cd /opt/anmanie/
wine AnmanieSMP.exe
