#!/bin/bash

#############################################################################
#
# Startscript for Teamspeak3
#
# Created  for Pardus
#
#############################################################################


cd /opt/teamspeak3/
./ts3client_runscript.sh
