#!/bin/bash

#############################################################################
#
# Startscript for ShapeCollage
#
# Created  for Pardus
#
#############################################################################


cd /usr/share/shapecollage/
./Shape\ Collage