#!/bin/bash

#############################################################################
#
# Startscript for Omnitux
#
# Created  for Pardus
#
#############################################################################


cd /usr/share/omnitux/
./omnitux-light.sh
