--- a/Makefile	2011-11-24 18:28:27.000000000 +0100
+++ b/Makefile	2011-11-24 18:42:25.793999977 +0100
@@ -1,5 +1,5 @@
 
-export prefix=/usr/local
+export prefix=/usr
 export milena_dir=$(prefix)/share/milena
 export doc_dir=$(prefix)/share/doc/milena
 export speechd_dir=$(shell ./find_speechd)
@@ -11,7 +11,6 @@
 
 all: config.dat
 	make -C src all
-	make -C data all
 	make -C utils all
 	make -C speechd all
 	make -C milena_ws all
@@ -24,18 +23,16 @@
 clean:
 	rm -f config.dat
 	make -C src clean
-	make -C data clean
 	make -C utils clean
 	make -C speechd clean
 	make -C milena_ws clean
 	make -C subplayer clean
 		
 install:
+	install -dm 0755 $(DESTDIR)$(prefix)/bin
+	install -dm 0755 $(DESTDIR)$(prefix)/lib/pkgconfig
+	install -dm 0755 $(DESTDIR)$(prefix)/include
 	make -C src install
-	ldconfig
-	mkdir -p $(doc_dir)
-	install -m 644 README* $(doc_dir)
-	make -C data install
 	make -C utils install
 	make -C milena_ws install
 	make -C subplayer install
